name: lucky_lucky
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  http: ^1.1.0
  provider: ^6.1.1
  html: ^0.15.4
  flutter_screenutil: ^5.9.0
  pull_to_refresh: ^2.0.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
